name: Bug Report
description: Report a bug in cc-notifier-voice
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Plugin version
      description: Run `cat plugin/.claude-plugin/plugin.json | grep version` to check.
      placeholder: "e.g. 0.2.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - WSL2 (Windows)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS version
      placeholder: "e.g. macOS 15.3, Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant settings from `~/.config/cc-notifier-voice/config` (redact any secrets).
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information (screenshots, log output, etc.).
