name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement. Please describe your idea below.

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem does this feature solve? What workflow would it improve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should this feature work? Include configuration examples if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered and why they are less suitable.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information, mockups, or references.
